### ISSUE TITLE
race-condition for click event listener and el.contains

### ISSUE THREAD

**Issue by kmohrf** [simplesmiler/vue-clickaway#10]
hi,

i just debugged a problem with a vue component I’m creating. it uses flatpickr to provide the user with a date selection. once i select a date from the datepicker it should set the date as value for the input and close itself. this (probably) works but my component that uses your directive is closed as well. here’s a picture of the setup:

![screenshot from 2017-01-26 02-18-06](https://cloud.githubusercontent.com/assets/580226/22316485/bcf19e38-e36d-11e6-8453-16d9575fb2dd.png)

while looking at your code i noticed that you use el.contains to check if you should call the callback. and as far as i can see the callback itself is executed once the click event reached `documentElement`. i added some code just before the callback executor, to look why the panel was closed.
`el` referred to my panel and `ev.target` referred to a span that represented a day inside the flatpickr calendar. but when I checked the `ev.target.parentNode` value it was `null`.

i guess what happens is the following:
* click on day span inside flatpickr → click event starts bubbling
* flatpickr click listener is called, sets the date and closes flatpickr (destroying the original day span element)
* click event continues to bubble
* click event reaches `documentElement` and is handled by vue-clickaway’s event listener
* it checks if the element contains the day span but as this has been removed from the dom, the check fails
* the callback is executed

i guess there’s no good workaround for this. what I usually did when I implemented this kind of behaviour is to check for `mouseenter` and `mouseleave` events on the target element. as long as no interaction triggered a `mouseleave` event any click listeners wouldn’t execute the callback.

**Comment by kmohrf** [comment]
using the mouseup event instead of click works for me, but it all comes down to the question if any event is used by something else down the dom tree to remove or move elements from the dom.

**Comment by simplesmiler** [comment]
Hi @kmohrf, thanks for the report.

I assume you have used `appendTo` option of flatpickr. You are right in the assumption that flatpickr dropdown element gets removed before the click event reaches the `document`, which makes the containment check fail.

The workaround I would go for is returning early in the away handler, if `ev.target.parentNode == null`. But I don't think this should be done from the `vue-clickaway` side.
