### ISSUE TITLE
Passing an arguments to function

### ISSUE THREAD

**Issue by rgbskills** [simplesmiler/vue-clickaway#11]
Is there any way to pass arguments to the away function?

this is what I would like to achieve:
`<p v-on-clickaway="away(arg1,arg2)" @click="click" :style="{ color: color }">{{ text }}</p>`

**Comment by simplesmiler** [comment]
Hi there.

This is only possible in Vue 1. Vue 2 simplified the directives, making them unable to accept statements like `away(arg1, arg2)`. Theoretically it's possible to parse and execute the statement anyway (like `v-on` internally does), but this is not implemented yet.

**Comment by simplesmiler** [comment]
A workaround (for modern browsers and/or transpiled code) is to use an arrow function.
`v-on-clickaway"() => away(arg1, arg2)"`

Note that this applies only to Vue 2.

**Comment by simplesmiler** [comment]
Closing this for now, as I don't think mimicking `v-on` would worth the effort, and there are minimal downsides to the `() => away(args)` approach.
