### ISSUE TITLE
when run your demo directive within a custom component's template, it does not work

### ISSUE THREAD

**Issue by cnweibo** [simplesmiler/vue-clickaway#4]
Hi, I have tested the demo code you provided, when nest your directive within customized component's template, it does not work.
Please check here:
https://jsfiddle.net/opsoafhz/

**Comment by simplesmiler** [comment]
Looks like you didn't save the fiddle properly :wink:

**Comment by cnweibo** [comment]
Sorry, please see this fiddle:
[https://jsfiddle.net/cdnrt49k/](https://jsfiddle.net/cdnrt49k/)

**Comment by simplesmiler** [comment]
This is because instances do not share data and assets with children.
You can approach this by either letting the child handle data: https://jsfiddle.net/cdnrt49k/
Or by letting the parent handle data: https://jsfiddle.net/cdnrt49k/2/

**Comment by cnweibo** [comment]
ok. Thank you. It is awsome for demonstrating vuejs custom directives.
