### ISSUE TITLE
Vue clickaway except spefic element

### ISSUE THREAD

**Issue by middle21** [simplesmiler/vue-clickaway#40]
Hello there.My problem is that I have an input (search bar) ; onfocus another element where search results would appear is displayed and I attached the v-on-clickaway directive to this element.

Every time I click on the input(to type my search keywords), the search results element dissapears.So basically I want that element to not dissapear whenever I click the input or the search results element.

It is possible to achieve this functionality ?
Thank you.

**Comment by diakonovm** [comment]
Call `event.stopPropagation()` on the element that you want to exclude.

**Comment by SebastianMieszczanczyk** [comment]
As @diakonovm said - you can use on your element:
e.g.
`@click.stop`

**Comment by middle21** [comment]
Thanks for the replies.Solved.

**Comment by mihaimdm22** [comment]
I have tried this solution but I'm using [vue-flatpickr](https://github.com/ankurk91/vue-flatpickr-component) component and that one uses it's own internals.

For more context I am using clickaway for my filters container which contains a few filters
```
 <div v-on-clickaway="onClickAway"
      class="absolute block inset-auto right-0 top-full bg-white min-w-300px mt-2 z-20 shadow-context rounded-xl"
      v-if="open"
    >

onClickAway() {
      this.open = false
    },
```

One of the filters sets a date via flatpickr
```
<flat-pickr
      :name="filter.id"
      :id="filter.id"
      @on-change="changeFilter"
      ref="field-input"
      class="w-full"
      v-model="value"
      :config="flatpickrConfig"
      :placeholder="filter.filter_configuration.placeholder"
    />
```

For some reason I can click on days of this flatpickr, but when I click on prev/next month or month/year selector it closes the filters container

I can send a video for more context
