### ISSUE TITLE
Issues with iOS

### ISSUE THREAD

**Issue by Franky47** [simplesmiler/vue-clickaway#7]
I'm using `vue-clickaway` in a SPA that will run on both desktop and mobile, to close popups and dismiss other kinds of UI elements.

It works wonderfully on desktop and android, but on iOS it seems like it does not detect clicks outside of the bounds of the whole page (for example when it does not extend to the bottom of the viewport).

Example:
http://secret-santa.surge.sh/sandbox

Somehow it works with the demo fiddle, so there may be something else going on in my app that throws vue-clickaway off course.

**Comment by simplesmiler** [comment]
This is weird. Two possible reasons I can think of:
- Broken event delegation.
- Clicks outside of bounds not arriving to `document.documentElement`.

I don't have access to an iOS device to test on, but I would like you to try a few things:
- Run this test: http://www.quirksmode.org/m/tests/eventdelegation.html (click on the div to change it multiple times).
- If possible, modify `document.documentElement` to be `document` (either inside of node_modules or in the downloaded from CDN fille).

**Comment by Franky47** [comment]
Event delegation test does not work at all on iOS indeed, so there's a good lead there.

It looks like this is a [known issue](http://www.quirksmode.org/blog/archives/2010/09/click_event_del.html).

**Comment by Franky47** [comment]
I was able to make it work by adding the following to my CSS:
```css
html, body {
    height: initial !important;
}
```

**Comment by simplesmiler** [comment]
Glad you found a solution.

**Comment by Franky47** [comment]
There still seems to be small areas where the click does not seem to do anything, but I could not find a repeatable pattern that makes it 100% reproducible, looks like it's a bit random. The UX is good enough in my case with this fix anyway.

Thanks for your help !

**Comment by RobWJacob** [comment]
i have the same problem, does not work on my ipad with ios 10.2.1
i tried the css hack, but does not work
works great on windows desktop and android
it looks like it works only on a minimal zone on the site
the http://www.quirksmode.org/m/tests/eventdelegation.html also does not work on ios

**Comment by jedu0309** [comment]
Fix this by add 'touchstart' event listener

**Comment by farzadso** [comment]
@jedu0309 Where did you add the `touchstart` event event listener to?
